CREATE TEMP TABLE tmp_a (VALUE INT);
CREATE TEMP TABLE tmp_b (VALUE INT);

INSERT INTO tmp_a (VALUE) VALUES (10);
INSERT INTO tmp_b (VALUE) VALUES (100);

SELECT
CASE
    WHEN EXISTS(SELECT 1 FROM tmp_a) THEN (SELECT * FROM tmp_a)
    WHEN EXISTS(SELECT 1 FROM tmp_b) THEN (SELECT * FROM tmp_b)
END
